export const storeProducts = [
	{
		id: 1,
		title: "BLOOMIN' MARVELLOUS - Illustration",
		img: "img/BLOOMINMARVELLOUSillo.png",
		price: 1.5,
		company: "katcha.fun",
		info: `Grow some joy this spring with a friendly reminder that the world is blooming and it's marvellous! 

    Perfect for Mother's Day, Father's Day or Easter or just a spontaneous declaration of admiration for your friends and family.`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon 'floral', 'flowers', 'insects', 'nature', 'wildlife', 'spring','seasonal', 'kids' ,'green', 'orange', 'purple', postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 2,
		title: "BLOOMIN' MARVELLOUS - Pattern",
		img: "img/BLOOMINMARVELLOUSpatt.png",
		price: 1.5,
		company: "Katcha.fun",
		info: `Grow some joy this spring with a friendly reminder that the world is blooming and it's marvellous! 

    Perfect for Mother's Day, Father's Day or Easter or just a spontaneous declaration of admiration for your friends and family.`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'floral', 'flowers', 'insects', 'nature', 'wildlife', 'spring','seasonal', 'kids', 'green', 'orange', 'purple',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 3,
		title: "BLOOMIN' MARVELLOUS - Text",
		img: "img/BLOOMINMARVELLOUStext.png",
		price: 1.5,
		company: "Katcha.fun",
		info: `Grow some joy this spring with a friendly reminder that the world is blooming and it's marvellous! 

    Perfect for Mother's Day, Father's Day or Easter or just a spontaneous declaration of admiration for your friends and family.`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'floral', 'flowers', 'insects', 'nature', 'wildlife', 'spring','seasonal', 'kids','green', 'orange', 'purple',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 4,
		title: "Autumnal Magic - Illustration",
		img: "img/AUTUMNALMAGICillo.png",
		price: 1.5,
		company: "katcha.fun",
		info: `Get all autumnal with these magic, but deadly funghis. Celebrate the turning of the seasons with all your friends!`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `text, quote, message, inspiration, aspiration, 'funny', 'punny', 'watercolour', 'nature', 'autumn', 'seasonal', 'mushrooms', 'leaves','red', 'orange', 'brown', 'yellow',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/loops.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 5,
		title: "Autumnal Magic - Pattern",
		img: "img/AUTUMNALMAGICpatt.png",
		price: 1.5,
		company: "katcha.fun",
		info: `Get all autumnal with these magic, but deadly funghis. Celebrate the turning of the seasons with all your friends!`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `text, quote, message, inspiration, aspiration, 'funny', 'punny', 'watercolour', 'nature', 'autumn', 'seasonal', 'mushrooms', 'leaves', 'red', 'orange', 'brown', 'yellow',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/loops.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 6,
		title: "Autumnal Magic - Text",
		img: "img/AUTUMNALMAGICtext.png",
		price: 1.5,
		company: "katcha.fun",
		info: `Get all autumnal with these magic, but deadly funghis. Celebrate the turning of the seasons with all your friends!`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `text, quote, message, inspiration, aspiration, 'funny', 'punny', 'watercolour', 'nature', 'autumn', 'seasonal', 'mushrooms', 'leaves', 'red', 'orange', 'brown', 'yellow',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/loops.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 7,
		title: "Bloody Dinosaur - Illustration",
		img: "img/BLOODYDINOillo.png",
		price: 1.5,
		company: "katcha.fun",
		info: `Dinosaurs are for everyone, and this collection of watercolour dinosaurs will definitely make that statement!`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `dinosaurs, kids cards, illustration, pattern, watercolour, 'funny', 'kawaii','pink', 'green', 'purple',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 8,
		title: "Bloody Dinosaur - Pattern",
		img: "img/BLOODYDINOpatt.png",
		price: 1.5,
		company: "katcha.fun",
		info: `Dinosaurs are for everyone, and this collection of watercolour dinosaurs will definitely make that statement!`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `dinosaurs, kids cards, illustration, pattern, watercolour,'funny', 'kawaii','pink', 'green', 'purple',postcard `,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 9,
		title: "Bloody Dinosaur - Text",
		img: "img/BloodyDinotext.png",
		price: 1.5,
		company: "katcha.fun",
		info: `Dinosaurs are for everyone, and this collection of watercolour dinosaurs will definitely make that statement!`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `dinosaurs, kids cards, illustration, pattern, watercolour, 'funny', 'kawaii', 'pink', 'green', 'purple',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 10,
		title: "Grow with it - Illustration",
		img: "img/GROWWITHITillo.png",
		price: 1.5,
		company: "katcha.fun",
		info: ` NEEDS TEXT HERE`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'leaves', 'nature', 'girl', 'funny', 'watering', 'growing', 'brown', 'green','peach',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 11,
		title: "Grow with it - Pattern",
		img: "img/GROWWITHITpatt.png",
		price: 1.5,
		company: "katcha.fun",
		info: ` NEEDS TEXT HERE`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'Acorn', 'nature', 'funny', 'growing', 'green',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 12,
		title: "Grow with it - Text",
		img: "img/GROWWITHITtext.png",
		price: 1.5,
		company: "katcha.fun",
		info: ` NEEDS TEXT HERE`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'Leaves', 'nature', 'funny', 'growing', 'green', 'brown',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 13,
		title: "Keep it Creepy - Illustration",
		img: "img/KEEPITCREEPYillo.png",
		price: 1.5,
		company: "katcha.fun",
		info: ` NEEDS TEXT HERE`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'Halloween', 'Sweets', 'Frogs', 'Bats', 'Broom', 'green', 'orange' , 'purple',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 14,
		title: "Keep it Creepy - Pattern",
		img: "img/KEEPITCREEPYpatt.png",
		price: 1.5,
		company: "katcha.fun",
		info: ` NEEDS TEXT HERE`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'Halloween', 'Sweets', 'Frogs', 'Bats', 'Broom','green', 'orange',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 15,
		title: "Keep it Creepy - Text",
		img: "img/KEEPITCREEPYtext.png",
		price: 1.5,
		company: "katcha.fun",
		info: ` NEEDS TEXT HERE`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon,'Halloween', 'Sweets', 'Frogs', 'Bats', 'Broom','green', 'orange' , 'purple',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 16,
		title: "Let Love Rain - Illustration",
		img: "img/LETLOVERAINillo.png",
		price: 1.5,
		company: "katcha.fun",
		info: `This little love note will brighten even the greyest of skies. Send your loved ones a message of adoration in these cold wet months of winter.

    Wonderful for Valentine's, special occasions or just a spontaneous declaration of admiration for your friends and family.`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon , valentine, 'galentine', 'love', 'hearts', 'get well soon', 'sad days', 'depression', 'mental health', 'happy', 'kids', 'funny' 'blue', 'red', 'grey',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 17,
		title: "Let Love Rain - Pattern",
		img: "img/LETLOVERAINpatt.png",
		price: 1.5,
		company: "katcha.fun",
		info: `This little love note will brighten even the greyest of skies. Send your loved ones a message of adoration in these cold wet months of winter.

    Wonderful for Valentine's, special occasions or just a spontaneous declaration of admiration for your friends and family.`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon 'valentine', valentine, 'galentine', 'love', 'hearts', 'get well soon', 'sad days', 'depression', 'mental health', 'happy', 'kids', 'funny','blue', 'red', 'grey',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 18,
		title: "Let Love Rain - Text",
		img: "img/LETLOVERAINtext.png",
		price: 1.5,
		company: "katcha.fun",
		info: `This little love note will brighten even the greyest of skies. Send your loved ones a message of adoration in these cold wet months of winter.

    Wonderful for Valentine's, special occasions or just a spontaneous declaration of admiration for your friends and family.`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, valentine, 'galentine', 'love', 'hearts', 'get well soon', 'sad days', 'depression', 'mental health', 'happy', 'kids', 'funny','blue', 'red', 'grey',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 19,
		title: "Let there be Cake - Illustration",
		img: "img/LETTHEREBECAKEillo.png",
		price: 1.5,
		company: "katcha.fun",
		info: ` NEEDS TEXT HERE`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, Birthday , Cup cake , Cheery , Party, Candles 'Birthday', 'Cake', 'Balloons', 'Party', 'Candles', 'green', 'pink' , 'brown',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 20,
		title: "Let there be Cake - Pattern",
		img: "img/LETTHEREBECAKEpatt.png",
		price: 1.5,
		company: "katcha.fun",
		info: ` NEEDS TEXT HERE`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, cake , Birthday , Cup cake , Cheery , Party, Candles, 'Birthday', 'Cup cake', 'Cheery', 'Party', 'Candles' ,'green', 'pink' , 'brown',postcard `,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 21,
		title: "Let there be Cake - Text",
		img: "img/LETTHEREBECAKEtext.png",
		price: 1.5,
		company: "katcha.fun",
		info: ` NEEDS TEXT HERE`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, Birthday , Cup cake , Cheery , Party, Candles, 'Birthday', 'Cup cake', 'Cheery', 'Party', 'Candles', 'green', 'pink' , 'brown',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 22,
		title: "Love Yourself - Illustration",
		img: "img/LOVEURSELFillo.png",
		price: 1.5,
		company: "katcha.fun",
		info: `Goofy hearts need goofy cards, send your weird love with these happy hearts.`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'red', 'blue','watercolour', 'funny', 'goofy', 'cute', 'pattern', 'valentine', 'anniversary', 'galentine', 'self love', 'love', 'hearts',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 23,
		title: "Love Yourself - Pattern",
		img: "img/LOVEURSELFpatt.png",
		price: 1.5,
		company: "katcha.fun",
		info: `Goofy hearts need goofy cards, send your weird love with these happy hearts.`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'red', 'white','watercolour', 'funny', 'goofy', 'cute', 'pattern', 'valentine', 'anniversary', 'galentine', 'self love', 'love', 'hearts',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 24,
		title: "Love Yourself - Text",
		img: "img/LOVEURSELFtext.png",
		price: 1.5,
		company: "katcha.fun",
		info: `Goofy hearts need goofy cards, send your weird love with these happy hearts.`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'watercolour', 'funny', 'goofy', 'cute', 'pattern', 'valentine', 'anniversary', 'galentine', 'self love', 'love', 'hearts', 'red', 'pink',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 25,
		title: "Mole Rat - Illustration",
		img: "img/MOLERATillo.png",
		price: 1.5,
		company: "katcha.fun",
		info: `A postcard that celebrates the launch of my kid's comic, The Ugliest, send this collection of sleeping naked mole rats and spread the cutest, ugliest, happiest love you ever did see.`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'watercolour', 'nature', 'wildlife', 'africa', 'funny', 'self love','brown', 'pink','yellow' ,postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 26,
		title: "Mole Rat - Pattern",
		img: "img/MOLERATpatt.png",
		price: 1.5,
		company: "katcha.fun",
		info: `A postcard that celebrates the launch of my kid's comic, The Ugliest, send this collection of sleeping naked mole rats and spread the cutest, ugliest, happiest love you ever did see.`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'watercolour', 'nature', 'wildlife', 'africa', 'funny', 'self love', 'brown', 'pink','yellow',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 27,
		title: "Mole Rat - Text",
		img: "img/MOLERATtext.png",
		price: 1.5,
		company: "katcha.fun",
		info: `A postcard that celebrates the launch of my kid's comic, The Ugliest, send this collection of sleeping naked mole rats and spread the cutest, ugliest, happiest love you ever did see.`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'watercolour', 'nature', 'wildlife', 'africa', 'funny', 'self love' 'brown', 'pink','yellow',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 28,
		title: "Peace and Love - Illustration",
		img: "img/PEACEANDLOVEillo.png",
		price: 1.5,
		company: "katcha.fun",
		info: ` NEEDS TEXT HERE`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'watercolour', 'nature', 'wildlife', 'funny', 'winter', 'chilly', 'blue', 'green','white',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 29,
		title: "Peace and Love - Pattern",
		img: "img/PEACEANDLOVEpatt.png",
		price: 1.5,
		company: "katcha.fun",
		info: ` NEEDS TEXT HERE`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'watercolour', 'nature', 'wildlife', 'funny', 'winter', 'chilly', 'blue', 'green','white',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 30,
		title: "Peace and Love - Text",
		img: "img/PEACEANDLOVEtext.png",
		price: 1.5,
		company: "katcha.fun",
		info: ` NEEDS TEXT HERE`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'watercolour', 'nature', 'wildlife', 'funny', 'winter', 'chilly', 'blue', 'green','white',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},

	{
		id: 31,
		title: "Quickly Prickly - Illustration",
		img: "img/QUICKLYPRICKLYillo.png",
		price: 1.5,
		company: "katcha.fun",
		info: `We all have friends in our life who just don't put up with anyone's shit. Celebrate them with this no nonsense cowgirl.`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'cactus', just a note, funny, humour, punny, horse, nature, wildlife, plants, floral, cute, woman, mental health'brown', green, orange, yellow, pink,postcard `,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 32,
		title: "Quickly Prickly - Pattern",
		img: "img/QUICKLYPRICKLYpatt.png",
		price: 1.5,
		company: "katcha.fun",
		info: `Do you know someone who can just get a little bit prickly, and you just love them for it? Plant lovers, people avoiders, everyone will love these narked off looking cacti.`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'cactus', 'nature', 'wildlife', 'funny', 'winter', 'chilly', green, orange, yellow, pink ,postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 33,
		title: "Quickly Prickly - Text",
		img: "img/QUICKLYPRICKLYtext.png",
		price: 1.5,
		company: "katcha.fun",
		info: `Do you know someone who can just get a little bit prickly, and you just love them for it? Plant lovers, people avoiders, everyone will love this `,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'cactus', 'nature', 'wildlife', 'funny', 'winter', 'chilly',green, orange, yellow, pink ,postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 34,
		title: "Read Me - Illustration",
		img: "img/READMEillo.png",
		price: 1.5,
		company: "katcha.fun",
		info: `The perfict postcard for book lovers, the ever devoted reader in their natural habitat! Send it out for World Book Day or to your favourite avid reader.`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'reading', 'world book day', 'early learning', 'mental health', 'just a note', 'hello', 'how are you', 'funny', 'books', 'gifts', 'bookmark','blue', 'red', 'yellow',postcard `,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 35,
		title: "Read Me - Pattern",
		img: "img/READMEpatt.png",
		price: 1.5,
		company: "katcha.fun",
		info: `The perfict postcard for book lovers, the ever devoted reader in their natural habitat! Send it out for World Book Day or to your favourite avid reader.`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'reading', 'world book day', 'early learning', 'mental health', 'just a note', 'hello', 'how are you', 'funny', 'books', 'gifts', 'bookmark', 'blue', 'red', 'yellow',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 36,
		title: "Read Me - Text",
		img: "img/READMEtext.png",
		price: 1.5,
		company: "katcha.fun",
		info: `The perfict postcard for book lovers, the ever devoted reader in their natural habitat! Send it out for World Book Day or to your favourite avid reader.`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'reading', 'world book day', 'early learning', 'mental health', 'just a note', 'hello', 'how are you', 'funny', 'books', 'gifts', 'bookmark','blue', 'red', 'yellow' ,postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 37,
		title: "Spring Forward - Illustration",
		img: "img/SPRINGFORWARDillo.png",
		price: 1.5,
		company: "katcha.fun",
		info: `Jump it to spring with these funny little frogs and send your pen pals hopping mad. A wonderful postcard for the oldest and youngest in your address book`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `nature, frogs, early learning, spring, wildlife, 'seasonal', 'kids', 'education', 'fun', 'blue', 'green',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 38,
		title: "Spring Forward - Pattern",
		img: "img/SPRINGFORWARDpatt.png",
		price: 1.5,
		company: "katcha.fun",
		info: `Jump it to spring with these funny little frogs and send your pen pals hopping mad. A wonderful postcard for the oldest and youngest in your address book`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `nature, frogs, early learning, spring, wildlife, 'seasonal', 'kids', 'education', 'fun', 'yellow', 'purple',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 39,
		title: "Spring Forward - Text",
		img: "img/SPRINGFORWARDtext.png",
		price: 1.5,
		company: "katcha.fun",
		info: `Jump it to spring with these funny little frogs and send your pen pals hopping mad. A wonderful postcard for the oldest and youngest in your address book`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `nature, frogs, early learning, spring, wildlife, 'seasonal', 'kids', 'education', 'fun', 'yellow', 'purple', 'yellow',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 40,
		title: "Sunshine Lies Ahead - Illustration",
		img: "img/SUNSHINELIESAHEADillo.png",
		price: 1.5,
		company: "katcha.fun",
		info: `The summer is joyous and these little sunshines know it, whether you're on your travels checking in with family, or want to send a happy ray of sunshine to cheer someone up then this is the postcard for you.`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, pattern, kawaii, whimsical, decorative,'orange', 'pink', 'yellow' ,'brown', 'pride', 'LGBTQI', 'gay rights', 'love',, 'galentine', 'valentine', 'equal rights', 'summer', 'happy', 'anniversary', 'sunshine', 'sunset', 'holiday', 'travels', 'bon voyage',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 41,
		title: "Sunshine Lies Ahead - Pattern",
		img: "img/SUNSHINELIESAHEADpatt.png",
		price: 1.5,
		company: "katcha.fun",
		info: `The summer is joyous and these little sunshines know it, whether you're on your travels checking in with family, or want to send a happy ray of sunshine to cheer someone up then this is the postcard for you.`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, pattern, kawaii, whimsical, decorative'pride', 'LGBTQI', 'gay rights', 'love', 'galentine', 'valentine', 'equal rights', 'summer', 'happy', 'anniversary', 'sunshine', 'sunset', 'holiday', 'travels', 'bon voyage' ,'orange', 'pink', 'yellow' ,'brown',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 42,
		title: "Sunshine Lies Ahead - Text",
		img: "img/SUNSHINELIESAHEADtext.png",
		price: 1.5,
		company: "katcha.fun",
		info: `The summer is joyous and these little sunshines know it, whether you're on your travels checking in with family, or want to send a happy ray of sunshine to cheer someone up then this is the postcard for you.`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, pattern, kawaii, whimsical, decorative, 'pride', 'LGBTQI', 'gay rights', 'love', 'galentine', 'valentine', 'equal rights', 'summer', 'happy', 'anniversary', 'sunshine', 'sunset', 'holiday', 'travels', 'bon voyage', 'orange', 'pink', 'yellow' ,'brown',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 43,
		title: "Tick Tock - Illustration",
		img: "img/TICKTOCKillo.png",
		price: 1.5,
		company: "katcha.fun",
		info: `Ring in any celebration with this naughty little mouse! It's a new day, a new year, a new start, whatever it might be this postcard set is the perfect commemoration!`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'mouse', 'new year', 'celebration', 'champagne', 'clock', 'party', 'happy new year', 'cheers', 'kids', 'funny', 'pink', 'red', 'purple',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 44,
		title: "Tick Tock - Pattern",
		img: "img/TICKTOCKpatt.png",
		price: 1.5,
		company: "katcha.fun",
		info: `Ring in any celebration with this naughty little mouse! It's a new day, a new year, a new start, whatever it might be this postcard set is the perfect commemoration!`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'mouse', 'new year', 'celebration', 'champagne', 'clock', 'party', 'happy new year', 'cheers', 'kids', 'funny' ,'pink', 'red', 'purple', postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 45,
		title: "Tick Tock - Text",
		img: "img/TICKTOCKtext.png",
		price: 1.5,
		company: "katcha.fun",
		info: `Ring in any celebration with this naughty little mouse! It's a new day, a new year, a new start, whatever it might be this postcard set is the perfect commemoration!`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'mouse', 'new year', 'celebration', 'champagne', 'clock', 'party', 'happy new year', 'cheers', 'kids', 'funny','pink', 'red', 'purple',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 46,
		title: "Wild Out There - Illustration",
		img: "img/WILDOUTTHEREillo.png",
		price: 1.5,
		company: "katcha.fun",
		info: `"Brighten up your walls and letterboxes with this spectacular imagination of a wild child. 

    A perfect pick me up for anyone in your life, the world is wild and colourful and full of joy!`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'just a note', 'funny', 'humour', 'nature', 'wildlife', 'plants', 'floral', 'cute', 'girl', 'diability awareness', 'mental health', 'jungle', 'tiger','green', 'red', 'yellow',postcard `,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 47,
		title: "Wild Out There - Pattern",
		img: "img/WILDOUTTHEREpatt.png",
		price: 1.5,
		company: "katcha.fun",
		info: `"Brighten up your walls and letterboxes with this spectacular imagination of a wild child. 

    A perfect pick me up for anyone in your life, the world is wild and colourful and full of joy!`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'just a note', 'funny', 'humour', 'nature', 'wildlife', 'plants', 'floral', 'cute', 'girl', 'diability awareness', 'mental health', 'jungle', 'tiger', 'green', 'red',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 48,
		title: "Wild Out There - Text",
		img: "img/WILDOUTTHEREtext.png",
		price: 1.5,
		company: "katcha.fun",
		info: `"Brighten up your walls and letterboxes with this spectacular imagination of a wild child. 

    A perfect pick me up for anyone in your life, the world is wild and colourful and full of joy!`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'just a note', 'funny', 'humour', 'nature', 'wildlife', 'plants', 'floral', 'cute', 'girl', 'diability awareness', 'mental health', 'jungle', 'tiger', 'green', 'red', 'yellow',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 49,
		title: "Worm Your Way Out - Illustration",
		img: "img/WORMYOURWAYOUTillo.png",
		price: 1.5,
		company: "katcha.fun",
		info: ` NEEDS TEXT HERE`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'tulip', 'nature', 'wildlife', 'funny', 'windmill', 'worm','brown', 'green','red' ,postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 50,
		title: "Worm Your Way Out - Pattern",
		img: "img/WORMYOURWAYOUTpatt.png",
		price: 1.5,
		company: "katcha.fun",
		info: ` NEEDS TEXT HERE`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'apple', 'nature', 'clouds', 'funny', 'worm', 'blue', 'green','red',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 51,
		title: "Worm Your Way Out - Text",
		img: "img/WORMYOURWAYOUTtext.png",
		price: 1.5,
		company: "katcha.fun",
		info: ` NEEDS TEXT HERE`,
		materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
		pricing: [
			"Order 1 - 5 postcards at €1.50 per card!",
			"Order 5 - 9 postcards at €1.40 per card!",
			"Order 10 - 15 postcards at €1.40 per card!",
			"Order 16 cards and get each card at a funtastic €1.15!",
			"Free worldwide shipping on all orders.",
		],
		tags: `illustration, kids illustration, fun, cute, cartoon, 'leaves', 'nature', 'wildlife', 'funny', 'flower', 'worm', 'brown', 'green','pink',postcard`,
		inCart: false,
		count: 0,
		total: 0,
		size: "Postcard",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: false,
		postageTotal: 0,
	},
	{
		id: 52,
		title: "The Ugliest",
		img: "img/comics/THEUGLIESTENGLISH.png",
		price: 7.5,
		company: "katcha.fun",
		info: `What does it really mean to be ugly, is it all to do with what you look like?

  Or is there more to it than that? Take a walk with this naked mole rat for the day and decide for yourself.
  
  This comic follows a day in the life of a naked molerat set in the heart of the north east of Africa. Celebrating resilience, ugliness and, empathy. Creatures and people of the deserts of Africa navigate this story about how we treat ourselves and others and the downfalls that come with flippant opinions.
  
  This comic is really a labour of love, and a dip into the comic ocean, so this comic is all in pencils and watercolour, though I am no letterer, so, for now, I will make do with a digital method for that!`,
		materials: `Printed in an A5 size, which is 8.27 x 5.83 inches for anyone in the US, printed in the UK on 115gsm recycled paper pages with a 300gsm recycled card cover and will be 20 pages, cover to back, with as little damage to our environment as possible!`,
		pricing: [],
		tags: `illustration, kids illustration, fun, cute, comic`,
		inCart: false,
		count: 0,
		total: 0,
		size: "A5 - Comic",
		digital: false,
		background: "img/swirls.svg",
		language: "English",
		postage: true,
		postageTotal: 0,
	},
	{
		id: 53,
		title: "Das Hässlichste",
		img: "img/comics/DasHaesslicste.png",
		price: 7.5,
		company: "katcha.fun",
		info: `Was bedeutet es wirklich, hässlich zu sein? Ist es nur, wie man aussieht oder wie man sich verhält? Folge diesem kleinen Nacktmull einen Tag durch Ostafrikanische Wüsten in diesem Kindercomic und entscheide dich selbst.   Mein Comic verfolgt einen Tag im Leben von einem, im Herzen Ostafrikas lebenden, Nacktmull. Zelebriert wird Resilienz, Hässlichkeit und Empathie. Kreaturen und Menschen aus den Wüsten Afrikas navigieren die Seiten dieser Geschichte, und erläutern wie wir uns selbst und andere behandeln und welche Konsequenzen mit leichtfertigen Vorurteilen einhergehen.`,
		materials: `Es ist A5-Format gedruckt, das für alle in den USA 8,27 x 5,83 Zoll beträgt. Es wird in Deutschland auf 130 g / m² Recyceltem-Papier mit einem 300 g / m² Recyceltem-Kartenumschlag gedruckt und umfasst 20 Seiten, Cover zu Cover!`,
		pricing: [],
		tags: `illustration, kids illustration, fun, cute, comic`,
		inCart: false,
		count: 0,
		total: 0,
		size: "A5 - Comic",
		digital: false,
		background: "img/swirls.svg",
		language: "Deutsch",
		postage: true,
		postageTotal: 0,
	},
	{
		id: 54,
		title: "PLANT GIRL",
		img: "img/prints/PLANTGIRLa5print.png",
		price: 6,
		company: "katcha.fun",
		info: `NEEDS TEXT HERE`,
		materials: `Smooth 400gsm card with a full-colour print, this print has a slight gloss to it which gives it a nice shine.
A5 Print - 210mm x 148mm`,
		pricing: [],
		tags: `home decor, decoration, art print, illustration, kids illustration, fun, cute, cartoon brown, green, print`,
		inCart: false,
		count: 0,
		total: 0,
		size: "A5 - Print",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: true,
		postageTotal: 0,
	},
	{
		id: 55,
		title: "CATURDAY NIGHT",
		img: "img/prints/CATURNIGHTa5print.png",
		price: 6,
		company: "katcha.fun",
		info: `"Celebrate the season of Netflix and chill with this happy TV flicking cat.
This listing is for an A5 art print featuring a cat enjoying the warm glow of the telly on a winter's night.
"`,
		materials: `Smooth 400gsm card with a full-colour print, this print has a slight gloss to it which gives it a nice shine.
A5 Print - 210mm x 148mm`,
		pricing: [],
		tags: `home decor, decoration, art print, illustration, kids illustration, fun, cute, cartoon, blue, yellow, print`,
		inCart: false,
		count: 0,
		total: 0,
		size: "A5 - Print",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: true,
		postageTotal: 0,
	},
	{
		id: 56,
		title: "MORNING MOUNTAINS",
		img: "img/prints/DAILYMOUNTAINSa5 Print.png",
		price: 6,
		company: "katcha.fun",
		info: `Too many plants, too little time. Add this piece to your never ending collection of cacti and succulents, and remember to take some time to take it easy and feed those plant babies. A girl who appreciates foliage over personage.`,
		materials: `Smooth 400gsm card with a full-colour print, this print has a slight gloss to it which gives it a nice shine.
A5 Print - 210mm x 148mm`,
		pricing: [],
		tags: `home decor, decoration, art print, illustration, kids illustration, fun, cute, cartoon, pink, brown, white, print `,
		inCart: false,
		count: 0,
		total: 0,
		size: "A5 - Print",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: true,
		postageTotal: 0,
	},
	{
		id: 57,
		title: "FELDBERG GIRL",
		img: "img/prints/FELDBERGGIRLa5print.png",
		price: 6,
		company: "katcha.fun",
		info: `An ode to the Schwarzwald and all it's wonderful pursuits, though let's not go focusing on the sporting ones ey. So enjoy the wonderful scenery without the physical exertion, and purchase this fine imagery to sooth your soul.`,
		materials: `Smooth 400gsm card with a full-colour print, this print has a slight gloss to it which gives it a nice shine.
A5 Print - 210mm x 148mm`,
		pricing: [],
		tags: `home decor, decoration, art print, illustration, kids illustration, fun, cute, cartoon, white, pink, blue print `,
		inCart: false,
		count: 0,
		total: 0,
		size: "A5 - Print",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: true,
		postageTotal: 0,
	},
	{
		id: 58,
		title: "NARRI NARRO",
		img: "img/prints/NarriNarroprinta5.png",
		price: 6,
		company: "katcha.fun",
		info: `In the Schwarzwald when the weather starts to turn and spring begins to break, the Hexen come out to play. Celebrate carnival and all things strange and comical with this Faschings themed print.`,
		materials: `Smooth 400gsm card with a full-colour print, this print has a slight gloss to it which gives it a nice shine.
A5 Print - 210mm x 148mm`,
		pricing: [],
		tags: `home decor, decoration, art print, illustration, kids illustration, fun, cute, cartoon, german culture, germany, fun, carnival, culture,red, blue, yellow, green, print `,
		inCart: false,
		count: 0,
		total: 0,
		size: "A5 - Print",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: true,
		postageTotal: 0,
	},
	{
		id: 59,
		title: "STRAWBERRY FIELDS FOREVER",
		img: "img/prints/STRAWBERRYFIELDSFOREVERa5print.png",
		price: 6,
		company: "katcha.fun",
		info: `Perfect decoration for a kids' room or a nursery, a representation of our ever temperamental summer weather and the joy every kid should experience of picking fresh fuirt.
Colourful art print inspired by the world around us and those small and adventurous minds it nurtures.`,
		materials: `Smooth 400gsm card with a full-colour print, this print has a slight gloss to it which gives it a nice shine.
A5 Print - 210mm x 148mm`,
		pricing: [],
		tags: `home decor, decoration, art print, illustration, kids illustration, fun, cute, cartoon, green, red, grey, print`,
		inCart: false,
		count: 0,
		total: 0,
		size: "A5 - Print",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: true,
		postageTotal: 0,
	},
	{
		id: 61,
		title: "DON'T BE BITTER - ADULTS",
		img: "img/prints/DON'TBEBITTERADULTS.png",
		price: 10,
		company: "katcha.fun",
		info: `This friendly motivational message is a scanned ink painting printed with text on a 400gsm smooth card for the best colours. 
Featuring the message ""Don't Be Bitter, It Gets Better"" these happy lemons are a great guide to thinking positively and trying not to stress too much. Though not a cure for the stressed overthinker. Perfect for yellow room decor and colourful people. Put a little sunshine in someone's day
`,
		materials: `Smooth 400gsm card with a full-colour print, this print has a slight gloss to it which gives it a nice shine.
A4 Print - 210mm x 297mm`,
		pricing: [],
		tags: `home decor, decoration, art print, illustration, kids illustration, fun, cute, cartoon, yellow, white, print`,
		inCart: false,
		count: 0,
		total: 0,
		size: "A4 - Print",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: true,
		postageTotal: 0,
	},
	{
		id: 62,
		title: "DON'T BE BITTER - Kids",
		img: "img/prints/DON'TBEBITTERKIDS.png",
		price: 10,
		company: "katcha.fun",
		info: `This friendly motivational message is a scanned ink painting printed with text on a 400gsm smooth card for the best colours. 
Featuring the message ""Don't Be Bitter, It Gets Better"" these happy lemons are a great guide to thinking positively and trying not to stress too much. Though not a cure for the stressed overthinker. Perfect for yellow room decor and colourful people. Put a little sunshine in someone's day
`,
		materials: `Smooth 400gsm card with a full-colour print, this print has a slight gloss to it which gives it a nice shine.
A4 Print - 210mm x 297mm`,
		pricing: [],
		tags: `home decor, decoration, art print, illustration, kids illustration, fun, cute, cartoonyellow, white, print`,
		inCart: false,
		count: 0,
		total: 0,
		size: "A4 - Print",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: true,
		postageTotal: 0,
	},
	{
		id: 63,
		title: "WILD CARDS",
		img: "img/activity/WILDCARDS.png",
		price: 10,
		company: "katcha.fun",
		info: `Tiny facts about large personalities of our natural world. These WILD CARDS will educate and inspire the youngest and oldest of humans. 
Get these tiny animals you can learn about, share the knowledge or trade them over, featuring different creatures large and small. 
Currently there are 11 different animals to collect with more becoming available in the future. A pack of these would slip nicely into a greetings card or a Christmas stocking.`,
		materials: `Six durable 400gsm laminated 85 x 55mm cards, with an illustrated animal on front and key information on the reverse.`,
		pricing: [],
		tags: `activity, trading, kids `,
		inCart: false,
		count: 0,
		total: 0,
		size: "Trading Cards",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: true,
		postageTotal: 0,
	},
	{
		id: 64,
		title: "KIDS ADDRESS BOOK",
		img: "img/activity/WILDCARDS.png",
		price: 10,
		company: "katcha.fun",
		info: `A great resource for any little writers in your lives, encourage them to write letters and improve their literacy skills.`,
		materials: `A6 interactive activity book, created on recycled card with full-colour images. There are only 4 different contact page styles currently available, in the future there will be more. Each address book contains 8 contact pages and a cover and back, it also comes with 1 matching postcard.`,
		pricing: [],
		tags: `activity, trading, kids, postcard `,
		inCart: false,
		count: 0,
		total: 0,
		size: "ACTIVITY BOOK",
		digital: false,
		background: "img/swirls.svg",
		language: "n/a",
		postage: true,
		postageTotal: 0,
	},
];

export const detailProduct = {
	id: 1,
	title: "BLOOMIN' MARVELLOUS - Illustration",
	img: "img/BLOOMINMARVELLOUSillo.png",
	price: 1.5,
	company: "katcha.fun",
	info: `Grow some joy this spring with a friendly reminder that the world is blooming and it's marvellous! 

  Perfect for Mother's Day, Father's Day or Easter or just a spontaneous declaration of admiration for your friends and family.`,
	materials: `This postcard is printed on high quality 330gsm FSC regulated A6 card with a matte front and a writable back.`,
	pricing: [
		"Order 1 - 5 postcards at €1.50 per card!",
		"Order 5 - 9 postcards at €1.40 per card!",
		"Order 10 - 15 postcards at €1.40 per card!",
		"Order 16 cards and get each card at a funtastic €1.15!",
		"Free worldwide shipping on all orders.",
	],
	tags: `illustration, kids illustration, fun, cute, cartoon 'floral', 'flowers', 'insects', 'nature', 'wildlife', 'spring','seasonal', 'kids' ,'green', 'orange', 'purple' postcard`,
	inCart: false,
	count: 0,
	total: 0,
	size: "Postcard",
	digital: false,
	background: "img/swirls.svg",
	language: "n/a",
	postage: false,
	postageTotal: 0,
};
