var Images = [
  { text: "", image: "img/illustrations/20200120_100502.jpg" },
  { text: "", image: "img/illustrations/20200309_114611.jpg" },
  {
    text: "",
    image: "img/illustrations/AmyMorrison-CatherineGreatTinder.png",
  },
  { text: "", image: "img/illustrations/BALLOONANIMALSCAT.jpg" },
  { text: "", image: "img/illustrations/BalloonasaurusRex.jpg" },
  { text: "", image: "img/illustrations/CACTUSINSTA.jpg" },
  { text: "", image: "img/illustrations/Catboy.jpg" },
  { text: "", image: "img/illustrations/chrisytinametx.jpg" },
  { text: "", image: "img/illustrations/Comics028.jpg" },
  { text: "", image: "img/illustrations/dino.jpg" },
  { text: "", image: "img/illustrations/DoggyDayCareAkeleyLogo.jpg" },
  { text: "", image: "img/illustrations/dont.jpg" },
  { text: "", image: "img/illustrations/FeldbergGirl.jpg" },
  { text: "", image: "img/illustrations/FOXINSNOW.jpg" },
  { text: "", image: "img/illustrations/FUNFORKIDS2.gif" },
  { text: "", image: "img/illustrations/GetawayBusLogoItunes.jpg" },
  { text: "", image: "img/illustrations/Grow.gif" },
  { text: "", image: "img/illustrations/HappilyGodless.gif" },
  { text: "", image: "img/illustrations/HappyBirthday Jelly.jpg" },
  { text: "", image: "img/illustrations/HBBALLOONFRONT.jpg" },
  { text: "", image: "img/illustrations/JANUARYMONTHLY.png" },
  { text: "", image: "img/illustrations/JOY3.jpg" },
  { text: "", image: "img/illustrations/judithkerr.jpg" },
  { text: "", image: "img/illustrations/KATCHA.FUN-KEEPGOING-RGB.jpg" },
  { text: "", image: "img/illustrations/LEMONPACK4.jpg" },
  { text: "", image: "img/illustrations/LOVEHEARTGROUP2.jpg" },
  { text: "", image: "img/illustrations/May4th2.gif" },
  { text: "", image: "img/illustrations/narrinarro.png" },
  { text: "", image: "img/illustrations/philpull.jpg" },
  { text: "", image: "img/illustrations/PizzaGirlA4.jpg" },
  { text: "", image: "img/illustrations/PlantGirlA4-AM.jpg" },
  { text: "", image: "img/illustrations/Sabine.jpg" },
  { text: "", image: "img/illustrations/SAMPLESMOOTH3.jpg" },
  { text: "", image: "img/illustrations/SHELLEY.jpg" },
  { text: "", image: "img/illustrations/sophmog.jpg" },
  { text: "", image: "img/illustrations/STARBG2RGB.jpg" },
  { text: "", image: "img/illustrations/StrawberryFieldsForeverA5.jpg" },
  { text: "", image: "img/illustrations/Tino.jpg" },
  { text: "", image: "img/illustrations/Untitled-1.jpg" },
  { text: "", image: "img/illustrations/Warmups-BigBud.jpg" },
  { text: "", image: "img/illustrations/WorkingGirl.jpg" },
  { text: "", image: "img/illustrations/worm.jpg" },
  { text: "", image: "img/illustrations/XMASsanta1y.jpg" },
];

export default Images;
